include: "rules/common.smk"
include: "rules/genome_assemblies.smk"

rule all:
    input:
        expand(
            "GENOMES/Sus_scrofa/Sscrofa11.1/lastal/{other_species}/{other_assembly_name}/GCA_000003025.6_{other_assembly_accession}.maf",
            zip,
            other_species=genomes['Species'],
            other_assembly_name=genomes['Assembly Name'],
            other_assembly_accession=genomes['Assembly Accession'],
        ),
        #expand(
        #    "GENOMES/Sus_scrofa/Sscrofa11.1/last_train/Sus_scrofa/Berkshire_pig_v1/GCA_000003025.6_GCA_001700575.1.train",
        #zip,
        #other_species=genomes['Species'],
        #other_assembly_name=genomes['Assembly Name'],
        #other_assembly_accession=genomes['Assembly Accession'],
        #),
        #expand(
        #    "GENOMES/{species}/{assembly_name}/lastdb/{assembly_accession}_{assembly_name}_genomic.prj",
        #    zip,
        #    species=genomes["Species"],
        #    assembly_accession=genomes["Assembly Accession"],
        #    assembly_name=genomes["Assembly Name"],
        #),
        #expand("GENOMES/Sus_scrofa/{assembly_name}/lastdb/{assembly_accession}_{assembly_name}_genomic.prj", assembly_name=config["ref_genomes"]["Sus_scrofa"]["assembly_name"],assembly_accession=config["ref_genomes"]["Sus_scrofa"]['assembly_accession'])
        #expand("GENOMES/{species}/{assembly_name}/blastdb/{assembly_accession}_{assembly_name}_genomic.ndb", zip, species='test',assembly_accession='test', assembly_name='test'),
        #expand("GENOMES/{species}/{assembly_name}/lastdb/{assembly_accession}_{assembly_name}_genomic.des", zip, species=genomes['Species'],assembly_accession=genomes['Assembly Accession'], assembly_name=genomes['Assembly Name']),
        #expand("GENOMES/{species}/{assembly_name}/blastdb/{assembly_accession}_{assembly_name}_genomic.ndb", zip, species=genomes['Species'],assembly_accession=genomes['Assembly Accession'], assembly_name=genomes['Assembly Name'])
        #expand("/lustre/home/bolner/data/genomes/{species}/{assembly_name}/blastdb/{assembly_accession}_{assembly_name}_genomic.fna.ndb", zip, species='test',assembly_accession='test', assembly_name='test'),
        #"/lustre/home/bolner/data/genomes/test/test/lastdb/test_test_genomic.fna.des"
        #"/lustre/home/bolner/data/genomes/Sus_scrofa/Sscrofa10.2/lastdb/GCF_000003025.5_Sscrofa10.2_genomic.fna.bck",
        #"/lustre/home/bolner/data/genomes/Sus_scrofa/Sscrofa10.2/blastdb/GCF_000003025.5_Sscrofa10.2_genomic.fna.ndb"
